name: Build and Release Electron App

on:
  push:
    tags:
      - 'v*'

jobs:
  build-release-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build app
        run: yarn build
      - name: Build installers (Windows)
        run: yarn dist
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Upload Release Assets (Windows)
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release/*.exe
            release/*.msi
            release/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-release-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build app
        run: yarn build
      - name: Build installers (Linux)
        run: yarn dist --linux
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Upload Release Assets (Linux)
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release/*.AppImage
            release/*.snap
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
